apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mibanco-backstage-app-docs
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
  #   github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:jeanramalinstructor
  lifecycle: experimental
